package luennot.live04.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static luennot.live04.Alkuluku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.20 18:55:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlkulukuTest {



  // Generated by ComTest BEGIN
  /** testMillaJaollinen15 */
  @Test
  public void testMillaJaollinen15() {    // Alkuluku: 15
    assertEquals("From: Alkuluku line: 16", 5, millaJaollinen(25)); 
    assertEquals("From: Alkuluku line: 17", 1, millaJaollinen(2)); 
    assertEquals("From: Alkuluku line: 18", 2, millaJaollinen(4)); 
    assertEquals("From: Alkuluku line: 19", 3, millaJaollinen(123)); 
    assertEquals("From: Alkuluku line: 20", 1, millaJaollinen(7)); 
  } // Generated by ComTest END
}