package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Etusuku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.10.03 09:48:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class EtusukuTest {



  // Generated by ComTest BEGIN
  /** testErota23 */
  @Test
  public void testErota23() {    // Etusuku: 23
    StringBuilder jono = new StringBuilder("123 456"); String s; 
    s = erota(jono,' ',false); assertEquals("From: Etusuku line: 25", "456", jono.toString()); assertEquals("From: Etusuku line: 25", "123", s); 
    s = erota(jono,' ',false); assertEquals("From: Etusuku line: 26", "", jono.toString()); assertEquals("From: Etusuku line: 26", "456", s); 
    jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 28", "1", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 29", "2", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 30", "3", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 31", "", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 32", "", erota(jono,' ',false)); 
    jono = new StringBuilder("123 456 789"); 
    assertEquals("From: Etusuku line: 34", "123 456", erota(jono,' ',true));
    assertEquals("From: Etusuku line: 35", "789", erota(jono,' ',true));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testErota62 */
  @Test
  public void testErota62() {    // Etusuku: 62
    StringBuilder jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 64", "1", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 65", "2", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 66", "3", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 67", "", erota(jono,' ')); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testErota80 */
  @Test
  public void testErota80() {    // Etusuku: 80
    StringBuilder jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 82", "1", erota(jono)); 
    assertEquals("From: Etusuku line: 83", "2", erota(jono)); 
    assertEquals("From: Etusuku line: 84", "3", erota(jono)); 
    assertEquals("From: Etusuku line: 85", "", erota(jono)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaAlkuLoppu101 */
  @Test
  public void testVaihdaAlkuLoppu101() {    // Etusuku: 101
    vaihdaAlkuLoppu("Aku Ankka", ' ', false).equals("Ankka Aku"); 
    vaihdaAlkuLoppu("Jukka Pekka Palo", ' ', true).equals("Palo Jukka Pekka"); 
    vaihdaAlkuLoppu("Aku", ' ', false).equals("Aku"); 
    vaihdaAlkuLoppu("", ' ', false).equals(""); 
    vaihdaAlkuLoppu("toimii.tama", '.', false).equals("tama.toimii"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaEtuSuku123 */
  @Test
  public void testVaihdaEtuSuku123() {    // Etusuku: 123
    assertEquals("From: Etusuku line: 124", "", vaihdaEtuSuku(""));
    assertEquals("From: Etusuku line: 125", "", vaihdaEtuSuku(" "));
    assertEquals("From: Etusuku line: 126", "Pele", vaihdaEtuSuku("Pele"));
    assertEquals("From: Etusuku line: 127", "Ankka Aku", vaihdaEtuSuku("Aku Ankka"));
    assertEquals("From: Etusuku line: 128", "Palo Jukka Pekka", vaihdaEtuSuku("Jukka Pekka Palo"));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaSukuEtu142 */
  @Test
  public void testVaihdaSukuEtu142() {    // Etusuku: 142
    assertEquals("From: Etusuku line: 143", "", vaihdaSukuEtu(""));
    assertEquals("From: Etusuku line: 144", "Pele", vaihdaSukuEtu("Pele"));
    assertEquals("From: Etusuku line: 145", "Aku Ankka", vaihdaSukuEtu("Ankka Aku"));
    assertEquals("From: Etusuku line: 146", "Jukka Pekka Palo", vaihdaSukuEtu("Palo Jukka Pekka"));
  } // Generated by ComTest END
}