package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d3.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.09.27 19:24:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {
}