package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d6.Taulukonkasittely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.10.23 00:47:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukonkasittelyTest {



  // Generated by ComTest BEGIN
  /** testPienimmanPaikka16 */
  @Test
  public void testPienimmanPaikka16() {    // Taulukonkasittely: 16
    int testiTaulukko[] = { 10,7,4,7,6,7} ; 
    assertEquals("From: Taulukonkasittely line: 18", 2, pienimmanPaikka(testiTaulukko)); 
    * int t[] = { 3,2,1,2,3} ; 
    assertEquals("From: Taulukonkasittely line: 21", 2, pienimmanPaikka(t)); 
  } // Generated by ComTest END
}