package demo.dd4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.dd4.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.10.09 18:09:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {
}