package demo.d5.test;
// Generated by ComTest BEGIN
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.10.13 19:20:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkioTest {



  // Generated by ComTest BEGIN
  /** testToString48 */
  @Test
  public void testToString48() {    // Henkio: 48
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkio line: 50", "Aku|Ankka|1934", aku.toString()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkio line: 52", "Pele||1940", pele.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi65 */
  @Test
  public void testGetNimi65() {    // Henkio: 65
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkio line: 67", "Aku Ankka", aku.getNimi()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkio line: 69", "Pele", pele.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSyntymavuosi80 */
  @Test
  public void testGetSyntymavuosi80() {    // Henkio: 80
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkio line: 82", 1934, aku.getSyntymavuosi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta94 */
  @Test
  public void testTulosta94() {    // Henkio: 94
    ByteArrayOutputStream byteoutput = new ByteArrayOutputStream(); 
    Henkilo hlo = new Henkilo("Aku","Ankka",1934); 
    hlo.tulosta(byteoutput); 
    { String _l_=byteoutput.toString(),_r_="Aku Ankka 1934\\s*"; if ( !_l_.matches(_r_) ) fail("From: Henkio line: 99" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse111 */
  @Test
  public void testParse111() {    // Henkio: 111
    Henkilo aku = new Henkilo("Roope","Ankka",1904); 
    aku.parse ("Roope|ankka|1904") == Roope Ankka 1904; 
  } // Generated by ComTest END
}